### PR TITLE
Consolidate .Admin, .Api and .Mobile

### LINKED ISSUE #505: ♻️ Refactor - Merge Admin, API into Mobile Repository
Cc: @matt-goldman @zacharykeeping @Anton-Polkanov 

To Myself,

### Pain

Currently, the API, Admin Portal, and Mobile UI are in separate repositories.

#### Admin
- [x] Code is in .Mobile Repo
- [x] Code builds
- [x] Code runs
- [x] CI/CD migrated to .Mobile
- [x] CI/CD tested
  
#### API
- [x] Code is in .Mobile Repo
- [x] Code Builds
- [x] Code Runs
- [x] CI/CD migrated to .Mobile
- [x] CI/CD tested  

- [x] Merge PR into .Mobile

#### Misc.

- [x] #506
- [x] Update F5 Experience
- [x] #547
- [x] #508
- [x] #548
- [x] #552 
- [x] zz Old repos
- [x] Move issues from old repos into this one

### Acceptance Criteria

- [ ] Meets Definition of Done
- [ ] No functionality regressions in process

Thanks!

### PR DESCRIPTION
**Pull request by tkapa**
Closes #505 

As per my conversation with @matt-goldman, our priority at the moment is to consolidate our repos:
`SSW.Rewards.Mobile` https://github.com/SSWConsulting/SSW.Rewards.Mobile
`SSW.Rewards.Admin` https://github.com/SSWConsulting/SSW.Rewards.Admin
`SSW.Rewards.API` https://github.com/SSWConsulting/SSW.Rewards.API

## Folder Structure

The goal is to position these repos in a fashion resembling Matt's .NET MAUI CA template. See the screenshot below to see the new folder structure.

For the purposes of this new structure I've renamed some projects.
From
    `SSW.Rewards.Mobile.csproj`
To
    `MobileUI.csproj`

From
    `UI.csproj` (SSW.Rewards.Admin UI)
To
    `AdminUI.csproj`

### `src/Common`
- `Shared.csproj`

### `src/Core`
- `/Application/SSW.Rewards.Application.csproj`
- `/Domain/SSW.Rewards.Domain.csproj`

### `src/Infrastructure`
- `SSW.Rewards.Infrastructure.csproj`

### `src/Presentation`
- `/WebAPI/WebAPI.csproj`
- `/UI`
    - `/MobileUI/MobileUI.csproj`
    - `/AdminUI/AdminUI.csproj`
  
image

**_Figure: new folder structure in SSW.Rewards.Mobile_**

## CI/CD

Adds the `.github/workflows` `.azure` and `infra` folders.

I've updated all workflow files with the project they came from. and done the same where relevant in the `infra` folder.

`.azure` is relevant to `.Admin`

### CODE REVIEW

**Comment by zacharykeeping** [comment]
Getting an error on build that "/SSW.Rewards/tests/Application.IntegrationTests/appsettings.json" could not be copied as it could not be found. Looks like this file went missing in this PR.

**Comment by tkapa** [comment]
> Getting an error on build that "/SSW.Rewards/tests/Application.IntegrationTests/appsettings.json" could not be copied as it could not be found. Looks like this file went missing in this PR.

@zacharykeeping looks like there is a `.gitignore` that wanted to make sure no `appsettings.json` was committed. I've made sure that only `appsettings.json` in the `src` folder are ignored for now.

**Review by AntPolkanov — APPROVED** [review]
LGTM. Checked that all projects are running.

**Comment by adamcogan** [comment]
⚠️ Have we lost the source code history?  If so, then we need to revert this.

**Pull request merged**
